steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/analytical-park-409304/hello:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/analytical-park-409304/hello:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/hello-world', 'hello-world-app-sha256-1=gcr.io/analytical-park-409304/hello:$COMMIT_SHA']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cicdgke'
